export type ElementCategory =
  | 'Backgrounds'
  | 'Objects'
  | 'Heroes'
  | 'Loaders'
  | 'Vector'
  | 'Shapes'
  | 'Isometric'
  | 'Avatars'
  | 'Monsters'
  | 'Elementals'
  | 'Textures'
  | 'Motion'
  | 'Effects'
  | 'Buttons'
  | '2.5D';

export interface ElementMeta {
  slug: string;
  name: string;
  description: string;
  category: ElementCategory;
  kind: 'three' | 'vector' | 'motion';
  keywords?: string[];
  install?: string;
}

export const elements: ElementMeta[] = [
  {
    slug: 'particle-field',
    name: 'Particle Field',
    description:
      'A drifting field of glowing particles with cursor parallax and depth fog. Perfect as a hero or section background.',
    category: 'Backgrounds',
    kind: 'three',
    keywords: ['particles', 'stars', 'background', 'points'],
  },
  {
    slug: 'wave-plane',
    name: 'Wave Plane',
    description:
      'An undulating wireframe ocean driven by layered sine waves in a custom vertex shader.',
    category: 'Backgrounds',
    kind: 'three',
    keywords: ['waves', 'shader', 'ocean', 'grid'],
  },
  {
    slug: 'grid-floor',
    name: 'Grid Floor',
    description:
      'An infinite scrolling neon grid floor with distance fade and glowing major lines. Retro synthwave energy.',
    category: 'Backgrounds',
    kind: 'three',
    keywords: ['grid', 'synthwave', 'floor', 'infinite'],
  },
  {
    slug: 'aurora-mesh',
    name: 'Aurora Mesh',
    description:
      'Soft blurred gradient blobs drifting like an aurora. A pure-SVG mesh gradient for hero backgrounds.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['gradient', 'mesh', 'blur', 'aurora'],
  },
  {
    slug: 'galaxy-spiral',
    name: 'Galaxy Spiral',
    description:
      'A procedural spiral galaxy of additive particles with inside-to-outside color mixing.',
    category: 'Backgrounds',
    kind: 'three',
    keywords: ['galaxy', 'spiral', 'space', 'particles'],
  },
  {
    slug: 'star-hyperspace',
    name: 'Star Hyperspace',
    description:
      'Warp-speed star streaks flying past the camera. A classic sci-fi travel effect.',
    category: 'Backgrounds',
    kind: 'three',
    keywords: ['warp', 'hyperspace', 'stars', 'speed'],
  },
  {
    slug: 'ripple-rings',
    name: 'Ripple Rings',
    description:
      'Concentric rings expanding upward like sonar pulses, viewed from a cinematic angle.',
    category: 'Backgrounds',
    kind: 'three',
    keywords: ['ripple', 'rings', 'radar', 'pulse'],
  },
  {
    slug: 'flow-field',
    name: 'Flow Field',
    description:
      'Thousands of streaks surfing a curl-noise field across the floor. Hypnotic motion.',
    category: 'Backgrounds',
    kind: 'three',
    keywords: ['flow', 'curl noise', 'streaks', 'field'],
  },
  {
    slug: 'torus-tunnel',
    name: 'Torus Tunnel',
    description:
      'An endless flight through rings of light with fog depth and gentle camera roll.',
    category: 'Backgrounds',
    kind: 'three',
    keywords: ['tunnel', 'rings', 'flight', 'endless'],
  },
  {
    slug: 'dot-terrain',
    name: 'Dot Terrain',
    description:
      'A landscape of thousands of dots rising and falling with traveling color peaks.',
    category: 'Backgrounds',
    kind: 'three',
    keywords: ['terrain', 'dots', 'landscape', 'wave'],
  },
  {
    slug: 'fog-drift',
    name: 'Fog Drift',
    description:
      'Soft fbm-noise fog drifting across your section. Layer it under content for depth.',
    category: 'Backgrounds',
    kind: 'three',
    keywords: ['fog', 'noise', 'fbm', 'smoke'],
  },
  {
    slug: 'distorted-sphere',
    name: 'Distorted Sphere',
    description:
      'An organic blob displaced by simplex noise in a custom shader, with fresnel rim lighting.',
    category: 'Objects',
    kind: 'three',
    keywords: ['blob', 'noise', 'sphere', 'organic'],
  },
  {
    slug: 'wireframe-globe',
    name: 'Wireframe Globe',
    description:
      'A rotating globe of latitude points connected by animated great-circle arcs.',
    category: 'Objects',
    kind: 'three',
    keywords: ['globe', 'earth', 'wireframe', 'network'],
  },
  {
    slug: 'liquid-knot',
    name: 'Liquid Knot',
    description:
      'A reflective torus knot with animated liquid distortion and studio environment lighting.',
    category: 'Objects',
    kind: 'three',
    keywords: ['torus', 'knot', 'metal', 'reflective'],
  },
  {
    slug: 'shard-crystal',
    name: 'Shard Crystal',
    description:
      'Low-poly crystal shards floating under studio lights with flat shading and fog.',
    category: 'Objects',
    kind: 'three',
    keywords: ['crystal', 'shards', 'low poly', 'gems'],
  },
  {
    slug: 'helix-strand',
    name: 'Helix Strand',
    description:
      'A double helix of particles with rotating rungs. Science-flavored hero accent.',
    category: 'Objects',
    kind: 'three',
    keywords: ['helix', 'dna', 'spiral', 'strand'],
  },
  {
    slug: 'pulse-ring',
    name: 'Pulse Ring',
    description:
      'Rings expanding outward from a pulsing core. A calm, focused loading state.',
    category: 'Loaders',
    kind: 'three',
    keywords: ['pulse', 'ring', 'loader', 'radar'],
  },
  {
    slug: 'wire-cube',
    name: 'Wire Cube',
    description:
      'Nested wireframe cubes tumbling in opposite directions. Technical loading indicator.',
    category: 'Loaders',
    kind: 'three',
    keywords: ['cube', 'wireframe', 'loader', 'tumble'],
  },
  {
    slug: 'monolith',
    name: 'Monolith',
    description:
      'A dark reflective slab rotating under a purple rim light. Mysterious centerpiece.',
    category: 'Objects',
    kind: 'three',
    keywords: ['monolith', 'slab', 'reflective', '2001'],
  },
  {
    slug: 'contour-lines',
    name: 'Contour Lines',
    description:
      'Procedural topographic contour rings generated with layered harmonics. Great for subtle texture.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['topography', 'contour', 'lines', 'texture'],
  },
  {
    slug: 'dot-matrix',
    name: 'Dot Matrix',
    description:
      'A radial dot grid that fades from the center out, with an accent dot at the core.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['dots', 'grid', 'pattern', 'halftone'],
  },
  {
    slug: 'radial-rays',
    name: 'Radial Rays',
    description:
      'A sunburst of tapered rays around a central core, with emphasis spokes every fourth ray.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['sunburst', 'rays', 'burst', 'badge'],
  },
  {
    slug: 'star-field',
    name: 'Star Field',
    description:
      'A scatter of four-point sparkle stars with gentle twinkling animation.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['stars', 'sparkles', 'twinkle', 'night'],
  },
  {
    slug: 'constellation-network',
    name: 'Constellation Network',
    description:
      'Drifting nodes that link into a living plexus as they approach each other.',
    category: 'Heroes',
    kind: 'three',
    keywords: ['plexus', 'network', 'nodes', 'connections'],
  },
  {
    slug: 'text-particles',
    name: 'Text Particles',
    description:
      'Your headline rendered from thousands of wave-animated particles sampled on a canvas.',
    category: 'Heroes',
    kind: 'three',
    keywords: ['text', 'typography', 'particles', 'headline'],
  },
  {
    slug: 'spotlight-stage',
    name: 'Spotlight Stage',
    description:
      'A metallic orb floating over an infinite grid, chased by a roaming spotlight.',
    category: 'Heroes',
    kind: 'three',
    keywords: ['spotlight', 'stage', 'orb', 'grid'],
  },
  {
    slug: 'ring-portal',
    name: 'Ring Portal',
    description:
      'A glowing portal ring with particles spiraling inward from deep space.',
    category: 'Heroes',
    kind: 'three',
    keywords: ['portal', 'ring', 'particles', 'spiral'],
  },
  {
    slug: 'floating-shapes',
    name: 'Floating Shapes',
    description:
      'Geometric primitives floating and slowly tumbling through space under soft studio lighting.',
    category: 'Heroes',
    kind: 'three',
    keywords: ['shapes', 'hero', 'geometry', 'float'],
  },
  {
    slug: 'orbit-loader',
    name: 'Orbit Loader',
    description:
      'A compact 3D loading indicator with orbiting rings, satellites, and a pulsing core.',
    category: 'Loaders',
    kind: 'three',
    keywords: ['loader', 'spinner', 'orbit', 'loading'],
  },
  {
    slug: 'wave-divider',
    name: 'Wave Divider',
    description:
      'Layered translucent waves flowing between sections. Stretches to any container width.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['divider', 'waves', 'section', 'flow'],
  },
  {
    slug: 'hex-pattern',
    name: 'Hex Pattern',
    description:
      'A honeycomb lattice with scattered accent cells. Clean tech texture for panels.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['hexagon', 'honeycomb', 'pattern', 'tech'],
  },
  {
    slug: 'topo-waves',
    name: 'Topo Waves',
    description:
      'Joy-division style stacked ridge lines with gaussian peaks and one accent ridge.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['ridges', 'joy division', 'waves', 'peaks'],
  },
  {
    slug: 'blob-shape',
    name: 'Blob Shape',
    description:
      'An organic gradient blob with soft glow and a slow rotation. Friendly hero decoration.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['blob', 'organic', 'gradient', 'shape'],
  },
  {
    slug: 'circuit-board',
    name: 'Circuit Board',
    description:
      'Orthogonal traces with pads and accent pathways. Perfect for engineering-themed art.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['circuit', 'pcb', 'traces', 'tech'],
  },
  {
    slug: 'chevron-pattern',
    name: 'Chevron Pattern',
    description:
      'Rows of downward chevrons with scattered accent arrows. Motion-friendly texture.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['chevron', 'arrows', 'pattern', 'rows'],
  },
  {
    slug: 'plus-grid',
    name: 'Plus Grid',
    description:
      'A grid of plus marks with an accent cluster at the core. Subtle Swiss-style texture.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['plus', 'cross', 'grid', 'swiss'],
  },
  {
    slug: 'retro-sun',
    name: 'Retro Sun',
    description:
      'A striped synthwave sun with warm gradient and glow. Instant 80s nostalgia.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['sun', 'synthwave', 'retro', 'stripes'],
  },
  {
    slug: 'corner-frame',
    name: 'Corner Frame',
    description:
      'Minimal corner brackets to spotlight or frame any content block.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['frame', 'corners', 'brackets', 'focus'],
  },
  {
    slug: 'scan-lines',
    name: 'Scan Lines',
    description:
      'A CRT-style scanline overlay with a subtle vertical density gradient.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['scanlines', 'crt', 'overlay', 'texture'],
  },
  {
    slug: 'zigzag-divider',
    name: 'Zigzag Divider',
    description:
      'A sharp zigzag section separator with solid fill. Stretches to any width.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['zigzag', 'divider', 'section', 'sharp'],
  },
  {
    slug: 'spiral-dots',
    name: 'Spiral Dots',
    description:
      'A phyllotaxis spiral grown from the golden angle, with scattered accent seeds.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['spiral', 'phyllotaxis', 'golden', 'sunflower'],
  },
  {
    slug: 'target-lock',
    name: 'Target Lock',
    description:
      'Counter-rotating dashed reticles with corner brackets and a pulsing center.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['target', 'crosshair', 'reticle', 'hud'],
  },
  {
    slug: 'arrow-flow',
    name: 'Arrow Flow',
    description:
      'Chevrons flowing forward with staggered opacity pulses. Directs the eye.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['arrows', 'chevrons', 'flow', 'direction'],
  },
  {
    slug: 'burst-star',
    name: 'Burst Star',
    description:
      'A starburst seal badge with a dark core and gentle rocking rotation.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['starburst', 'seal', 'badge', 'sticker'],
  },
  {
    slug: 'wave-lines',
    name: 'Wave Lines',
    description:
      'Rows of sine waves drifting horizontally at different speeds and phases.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['waves', 'sine', 'lines', 'drift'],
  },
  {
    slug: 'perspective-grid',
    name: 'Perspective Grid',
    description:
      'A one-point perspective floor grid converging on an accent horizon line.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['perspective', 'grid', 'horizon', 'floor'],
  },
  {
    slug: 'concentric-dots',
    name: 'Concentric Dots',
    description:
      'Dashed concentric rings of round dots with one accent ring. Radar-like focus.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['concentric', 'rings', 'dots', 'radar'],
  },
  {
    slug: 'diagonal-stripes',
    name: 'Diagonal Stripes',
    description:
      'A field of diagonal stripes with sparse accent bars. Bold industrial texture.',
    category: 'Vector',
    kind: 'vector',
    keywords: ['stripes', 'diagonal', 'hazard', 'industrial'],
  },
  {
    slug: 'shape-rings',
    name: 'Rings',
    description:
      'Overlapping translucent rings breathing at different rhythms.',
    category: 'Shapes',
    kind: 'vector',
    keywords: ['rings', 'circles', 'overlap', 'breathing'],
  },
  {
    slug: 'shape-arcs',
    name: 'Arc Tiles',
    description:
      'A Bauhaus tile mosaic of quarter-arcs, dots, squares, and diamonds.',
    category: 'Shapes',
    kind: 'vector',
    keywords: ['bauhaus', 'tiles', 'arcs', 'mosaic'],
  },
  {
    slug: 'shape-triangles',
    name: 'Triangle Mosaic',
    description:
      'An alternating up/down triangle weave with layered opacities.',
    category: 'Shapes',
    kind: 'vector',
    keywords: ['triangles', 'mosaic', 'weave', 'pattern'],
  },
  {
    slug: 'shape-ribbon',
    name: 'Ribbons',
    description:
      'Gradient ribbons flowing across the canvas with morphing curves.',
    category: 'Shapes',
    kind: 'vector',
    keywords: ['ribbon', 'flow', 'gradient', 'curve'],
  },
  {
    slug: 'shape-waves',
    name: 'Wave Bands',
    description:
      'Layered wave bands fading into depth. A calm section footer.',
    category: 'Shapes',
    kind: 'vector',
    keywords: ['waves', 'bands', 'layers', 'depth'],
  },
  {
    slug: 'shape-confetti',
    name: 'Confetti',
    description:
      'A seeded scatter of tumbling rects, circles, and triangles. Celebration ready.',
    category: 'Shapes',
    kind: 'vector',
    keywords: ['confetti', 'party', 'scatter', 'celebration'],
  },
  {
    slug: 'iso-cube',
    name: 'Iso Cubes',
    description:
      'Stacked isometric cubes in a step arrangement. The hello-world of iso art.',
    category: 'Isometric',
    kind: 'vector',
    keywords: ['isometric', 'cube', 'stack', '3d'],
  },
  {
    slug: 'iso-tower',
    name: 'Iso Tower',
    description:
      'An isometric skyscraper with glowing window grids and a rooftop unit.',
    category: 'Isometric',
    kind: 'vector',
    keywords: ['isometric', 'building', 'tower', 'city'],
  },
  {
    slug: 'iso-server',
    name: 'Iso Server',
    description:
      'An isometric server rack with blinking status LEDs across its bays.',
    category: 'Isometric',
    kind: 'vector',
    keywords: ['isometric', 'server', 'rack', 'devops'],
  },
  {
    slug: 'iso-trees',
    name: 'Iso Trees',
    description:
      'Low-poly isometric trees on a grass platform. Cozy game-map vibes.',
    category: 'Isometric',
    kind: 'vector',
    keywords: ['isometric', 'trees', 'nature', 'platform'],
  },
  {
    slug: 'iso-boxes',
    name: 'Iso Boxes',
    description:
      'Cardboard parcels stacked in isometric view with tape details.',
    category: 'Isometric',
    kind: 'vector',
    keywords: ['isometric', 'boxes', 'package', 'delivery'],
  },
  {
    slug: 'avatar-initials',
    name: 'Avatar Initials',
    description:
      'Gradient rounded-square avatar with centered initials. Zero-config fallback.',
    category: 'Avatars',
    kind: 'vector',
    keywords: ['avatar', 'initials', 'gradient', 'profile'],
  },
  {
    slug: 'avatar-pixel',
    name: 'Avatar Pixel',
    description:
      'A mirrored pixel identicon generated deterministically from any seed.',
    category: 'Avatars',
    kind: 'vector',
    keywords: ['avatar', 'identicon', 'pixel', 'generated'],
  },
  {
    slug: 'avatar-blob',
    name: 'Avatar Blob',
    description:
      'A friendly blob character with swappable eyes and mouth variants.',
    category: 'Avatars',
    kind: 'vector',
    keywords: ['avatar', 'blob', 'cute', 'character'],
  },
  {
    slug: 'avatar-shapes',
    name: 'Avatar Shapes',
    description:
      'A Bauhaus-style abstract portrait composed from primitive shapes.',
    category: 'Avatars',
    kind: 'vector',
    keywords: ['avatar', 'abstract', 'bauhaus', 'geometric'],
  },
  {
    slug: 'avatar-status',
    name: 'Avatar Status',
    description:
      'A presence-aware avatar placeholder with online ring and status dot.',
    category: 'Avatars',
    kind: 'vector',
    keywords: ['avatar', 'status', 'presence', 'online'],
  },
  {
    slug: 'avatar-cat',
    name: 'Avatar Cat',
    description:
      'A minimal cat face with twitching whiskers, blush, and triangle ears.',
    category: 'Avatars',
    kind: 'vector',
    keywords: ['avatar', 'cat', 'animal', 'cute'],
  },
  {
    slug: 'avatar-robot',
    name: 'Avatar Robot',
    description:
      'A friendly robot head with blinking visor eyes and a glowing antenna.',
    category: 'Avatars',
    kind: 'vector',
    keywords: ['avatar', 'robot', 'bot', 'sci-fi'],
  },
  {
    slug: 'avatar-animal',
    name: 'Avatar Animal',
    description:
      'Bear, panda, frog, and fox faces from one generator with a variant option.',
    category: 'Avatars',
    kind: 'vector',
    keywords: ['avatar', 'animals', 'bear', 'panda', 'frog', 'fox'],
  },
  {
    slug: 'avatar-orbit',
    name: 'Avatar Orbit',
    description:
      'Initials inside two elliptical orbits with satellites circling at different speeds.',
    category: 'Avatars',
    kind: 'vector',
    keywords: ['avatar', 'orbit', 'space', 'initials'],
  },
  {
    slug: 'avatar-ring',
    name: 'Story Ring',
    description:
      'An animated gradient story ring around a dark initial disc.',
    category: 'Avatars',
    kind: 'vector',
    keywords: ['avatar', 'story', 'ring', 'gradient'],
  },
  {
    slug: 'monster-ember',
    name: 'Emberling',
    description:
      'A fire-type chibi companion with a flickering flame tail. Original creature.',
    category: 'Monsters',
    kind: 'vector',
    keywords: ['monster', 'fire', 'chibi', 'creature'],
  },
  {
    slug: 'monster-tide',
    name: 'Tideling',
    description:
      'A water-type chibi companion with fin ears and a fan tail. Original creature.',
    category: 'Monsters',
    kind: 'vector',
    keywords: ['monster', 'water', 'chibi', 'creature'],
  },
  {
    slug: 'monster-sprout',
    name: 'Sproutling',
    description:
      'A grass-type chibi companion with a sprout on its head. Original creature.',
    category: 'Monsters',
    kind: 'vector',
    keywords: ['monster', 'grass', 'chibi', 'creature'],
  },
  {
    slug: 'monster-zap',
    name: 'Zapling',
    description:
      'An electric-type chibi companion with bolt ears and a lightning tail.',
    category: 'Monsters',
    kind: 'vector',
    keywords: ['monster', 'electric', 'chibi', 'creature'],
  },
  {
    slug: 'monster-wisp',
    name: 'Wispling',
    description:
      'A ghost-type chibi spirit that gently floats above the ground.',
    category: 'Monsters',
    kind: 'vector',
    keywords: ['monster', 'ghost', 'spirit', 'floating'],
  },
  {
    slug: 'capture-core',
    name: 'Capture Core',
    description:
      'An original capture-device orb with hex-tech seams and a pulsing core.',
    category: 'Monsters',
    kind: 'vector',
    keywords: ['orb', 'capture', 'device', 'collector'],
  },
  {
    slug: 'texture-static',
    name: 'TV Static',
    description: 'Rapid-cycling fractal noise straight out of an analog television.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-paper',
    name: 'Paper Fiber',
    description: 'Warm lit paper grain from fractal noise and a distant light.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-marble',
    name: 'Marble Veins',
    description: 'Displaced vein strokes flowing like polished dark marble.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-halftone',
    name: 'Halftone Print',
    description: 'Print-style dot field that swells toward the center of the canvas.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-plaid',
    name: 'Plaid Weave',
    description: 'Layered translucent bands crossing into classic flannel plaid.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-carbon',
    name: 'Carbon Fiber',
    description: 'Alternating woven highlights mimicking carbon-fiber sheeting.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-blueprint',
    name: 'Blueprint Grid',
    description: 'Minor/major engineering grid with a dashed drafting circle.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-watercolor',
    name: 'Watercolor Wash',
    description: 'Displaced, blurred pigment blobs slowly rotating on paper.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-grain',
    name: 'Film Grain',
    description: 'Desaturated noise in overlay blend — drop it over any hero for film feel.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-sand',
    name: 'Sand Speckle',
    description: 'Nine hundred deterministic speckles over a warm dune gradient.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-knit',
    name: 'Knit Stitches',
    description: 'Hand-drawn V-loop stitches with light and shade for cozy fabric.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-fog',
    name: 'Drifting Fog',
    description: 'Screen-blended fog layer whose noise frequency slowly breathes.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'elemental-flame',
    name: 'Flame Elemental',
    description: 'A living flame with a morphing body and rising embers.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'elemental-tide',
    name: 'Tide Elemental',
    description: 'A water being whose body is an ocean of animated waves.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'elemental-terra',
    name: 'Terra Elemental',
    description: 'A stone golem with glowing core cracks and orbiting rubble.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'elemental-gale',
    name: 'Gale Elemental',
    description: 'A wind sprite of layered gusts with drifting cloud wisps.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'elemental-volt',
    name: 'Volt Elemental',
    description: 'A storm spark with crackling arcs pulsing around it.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'elemental-frost',
    name: 'Frost Elemental',
    description: 'A rotating six-armed snowflake spirit with sparkling shards.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'elemental-magma',
    name: 'Magma Elemental',
    description: 'A cooled lava shell with veins that pulse molten light.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'elemental-lumen',
    name: 'Lumen Elemental',
    description: 'A radiant sun-sprite with slowly rotating rays.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'elemental-umbra',
    name: 'Umbra Elemental',
    description: 'A shadow phantom with violet eyes and dissolving wisps.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'motion-text-reveal',
    name: 'Text Reveal',
    description: 'Characters rise out of overflow masks with staggered easing. Powered by GSAP.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-words-slide',
    name: 'Words Slide',
    description: 'Word-by-word slide-up with a back-out pop on the accent word.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-scroll-reveal',
    name: 'Scroll Reveal',
    description: 'Cards fade and rise as they enter the viewport via ScrollTrigger batching.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-parallax-layers',
    name: 'Parallax Layers',
    description: 'Depth-tagged layers drifting at different scroll speeds with scrub.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-magnetic-button',
    name: 'Magnetic Button',
    description: 'A button attracted to the cursor with elastic snap-back using quickTo.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-counter-roll',
    name: 'Counter Roll',
    description: 'A number counting up to its target when scrolled into view.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-marquee-loop',
    name: 'Marquee Loop',
    description: 'A seamless infinite marquee built from a duplicated track and xPercent tween.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-letter-scramble',
    name: 'Letter Scramble',
    description: 'Glyphs scramble then decode left-to-right on hover or focus.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-elastic-drag',
    description: 'Draggable card that springs back to origin with elastic ease on release.',
    name: 'Elastic Drag',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'button-glow',
    name: 'Glow Button',
    description: 'Primary CTA with a gradient face and dual-layer hover glow.',
    category: 'Buttons',
    kind: 'motion',
  },
  {
    slug: 'button-neon-outline',
    name: 'Neon Outline Button',
    description: 'Outlined neon button whose fill wipes across on hover.',
    category: 'Buttons',
    kind: 'motion',
  },
  {
    slug: 'button-glass',
    name: 'Glass Button',
    description: 'Frosted pill button floating over an animated gradient field.',
    category: 'Buttons',
    kind: 'motion',
  },
  {
    slug: 'button-loading',
    name: 'Loading Button',
    description: 'Idle → spinner → success state machine, ready to wire to real work.',
    category: 'Buttons',
    kind: 'motion',
  },
  {
    slug: 'button-icon-slide',
    name: 'Icon Slide Button',
    description: 'Arrow swaps to an accent copy by sliding through a clipped window.',
    category: 'Buttons',
    kind: 'motion',
  },
  {
    slug: 'button-social-circle',
    name: 'Social Circles',
    description: 'Four social icons lifting with spring easing and glow on hover.',
    category: 'Buttons',
    kind: 'motion',
  },
  {
    slug: 'button-border-trace',
    name: 'Border Trace Button',
    description: 'Gradient border draws itself clockwise around the button on hover.',
    category: 'Buttons',
    kind: 'motion',
  },
  {
    slug: 'button-elastic-press',
    name: 'Elastic Press Button',
    description: 'Chunky 3D press with a hard shadow collapse on click.',
    category: 'Buttons',
    kind: 'motion',
  },
  {
    slug: 'effect-glass-card',
    name: 'Glass Card',
    description: 'Frosted backdrop-blur card over a rotating conic gradient.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-neon-text',
    name: 'Neon Text',
    description: 'Layered text-shadow neon sign with an organic flicker loop.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-gradient-border-spin',
    name: 'Rotating Border',
    description: 'Conic-gradient border spinning around a card via @property angle.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-shimmer-skeleton',
    name: 'Shimmer Skeleton',
    description: 'Loading skeleton with a diagonal shimmer sweep across placeholders.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-spotlight-card',
    name: 'Spotlight Card',
    description: 'Radial spotlight tracks the cursor through CSS custom properties.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-glitch-text',
    name: 'Glitch Text',
    description: 'RGB-split glitch using clip-path slices on pseudo-elements.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-flip-card',
    name: 'Flip Card',
    description: 'True 3D flip revealing a gradient back face on hover.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-aurora-border',
    name: 'Aurora Border',
    description: 'Blurred conic aurora leaking around an inner panel edge.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-blob-morph',
    name: 'Blob Morph',
    description: 'Organic border-radius morphing with a slow hue rotation.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-gradient-text-flow',
    name: 'Gradient Text Flow',
    description: 'Background-clip text with a gradient endlessly flowing through it.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-typing-dots',
    name: 'Typing Dots',
    description: 'Chat-style typing indicator with bouncing dots inside a pill.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'monster-golem',
    name: 'Golemling',
    description: 'A stone chibi with glowing windows and moss patches.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-toxic',
    name: 'Toxiling',
    description: 'A slime chibi bubbling with toxic lime energy.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-crystal',
    name: 'Crystaling',
    description: 'A faceted gem chibi floating above the ground.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-fluff',
    name: 'Fluffling',
    description: 'A cloud puff that blinks slowly and bobs on the breeze.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-bubble',
    name: 'Bubbling',
    description: 'A translucent bubble spirit blowing tiny bubbles of its own.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-shroom',
    name: 'Shroomling',
    description: 'A spotted toadstool cap monster swaying on stubby roots.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-fangling',
    name: 'Fangling',
    description: 'A flappy-winged bat with fangs and glowing amber eyes.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-cactling',
    name: 'Cactling',
    description: 'A potted-looking cactus with needle arms and a lightning friend.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-drakeling',
    name: 'Drakeling',
    description: 'A tiny dragon with flapping wings and a head flame.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-starning',
    name: 'Starning',
    description: 'A five-point star that twinkles, blinks, and rocks in place.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-wormling',
    name: 'Wormling',
    description: 'A wiggly segmented garden worm with a happy face.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-mothling',
    name: 'Mothling',
    description: 'A fuzzy moth with patterned wings that flap and curling antennae.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-sluggo',
    name: 'Sluggo',
    description: 'A lime slug with googly eye stalks that sway independently.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-beetle',
    name: 'Boltbeetle',
    description: 'An electric rhinoceros beetle with a crackling yellow horn.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-jelly',
    name: 'Jellyling',
    description: 'A jellyfish whose six tentacles ripple out of phase.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'monster-koiling',
    name: 'Koiling',
    description: 'A calico koi that rocks mid-swim with rising bubbles.',
    category: 'Monsters',
    kind: 'vector',
  },
  {
    slug: 'avatar-ghost',
    name: 'Avatar Ghost',
    description: 'A friendly wavy-hem ghost that floats gently.',
    category: 'Avatars',
    kind: 'vector',
  },
  {
    slug: 'avatar-slime',
    name: 'Avatar Slime',
    description: 'A squishy slime blob that jiggles and drips.',
    category: 'Avatars',
    kind: 'vector',
  },
  {
    slug: 'avatar-wizard',
    name: 'Avatar Wizard',
    description: 'Star-tipped wizard hat over a warm glowing face.',
    category: 'Avatars',
    kind: 'vector',
  },
  {
    slug: 'avatar-knight',
    name: 'Avatar Knight',
    description: 'Visored helmet with blinking eyeslit lights.',
    category: 'Avatars',
    kind: 'vector',
  },
  {
    slug: 'avatar-owl',
    name: 'Avatar Owl',
    description: 'Wide ringed eyes, beak, and feather tufts.',
    category: 'Avatars',
    kind: 'vector',
  },
  {
    slug: 'avatar-penguin',
    name: 'Avatar Penguin',
    description: 'A waddling tuxedo bird with orange feet.',
    category: 'Avatars',
    kind: 'vector',
  },
  {
    slug: 'avatar-bunny',
    name: 'Avatar Bunny',
    description: 'Long inner-pink ears, whiskers, and blush.',
    category: 'Avatars',
    kind: 'vector',
  },
  {
    slug: 'avatar-tiger',
    name: 'Avatar Tiger',
    description: 'Striped orange fur with a cream muzzle.',
    category: 'Avatars',
    kind: 'vector',
  },
  {
    slug: 'avatar-alien',
    name: 'Avatar Alien',
    description: 'Big glossy black almond eyes on a green head.',
    category: 'Avatars',
    kind: 'vector',
  },
  {
    slug: 'avatar-mushroom',
    name: 'Avatar Mushroom',
    description: 'Spotted toadstool cap over a smiling stalk.',
    category: 'Avatars',
    kind: 'vector',
  },
  {
    slug: 'texture-brick',
    name: 'Brick Wall',
    description: 'Offset running-bond bricks over visible mortar lines.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-denim',
    name: 'Denim Twill',
    description: 'Crossing diagonal twill threads in layered blues.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-cork',
    name: 'Cork Grain',
    description: 'Deterministic rotated flecks pressed into cork board.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'texture-terrazzo',
    name: 'Terrazzo Chips',
    description: 'Rects, circles, and triangles scattered as terrazzo aggregate.',
    category: 'Textures',
    kind: 'vector',
  },
  {
    slug: 'elemental-blizzard',
    name: 'Blizzard Elemental',
    description: 'A snow spirit inside a swirling flurry of flakes.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'elemental-quake',
    name: 'Quake Elemental',
    description: 'A trembling rock mass cracking with molten seams.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'elemental-thorn',
    name: 'Thorn Elemental',
    description: 'Growing vines with thorns and blooming buds.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'elemental-echo',
    name: 'Echo Elemental',
    description: 'A sound core emitting expanding pulse rings.',
    category: 'Elementals',
    kind: 'vector',
  },
  {
    slug: 'iso-desk',
    name: 'Iso Desk Setup',
    description: 'An isometric dev desk with code screen and coffee steam.',
    category: 'Isometric',
    kind: 'vector',
  },
  {
    slug: 'iso-gift',
    name: 'Iso Gift',
    description: 'A floating wrapped present with a ribbon bow.',
    category: 'Isometric',
    kind: 'vector',
  },
  {
    slug: 'iso-house',
    name: 'Iso House',
    description: 'A tiny isometric home with a smoking chimney.',
    category: 'Isometric',
    kind: 'vector',
  },
  {
    slug: 'shape-stairs',
    name: 'Stairs',
    description: 'Stepped color blocks rising across the frame.',
    category: 'Shapes',
    kind: 'vector',
  },
  {
    slug: 'shape-dunes',
    name: 'Dunes',
    description: 'Layered sand dune bands drifting slowly.',
    category: 'Shapes',
    kind: 'vector',
  },
  {
    slug: 'shape-pill-grid',
    name: 'Pill Grid',
    description: 'Seeded scatter of rounded pills in mixed colors.',
    category: 'Shapes',
    kind: 'vector',
  },
  {
    slug: 'matrix-rain',
    name: 'Matrix Rain',
    description: 'Falling glyph columns on canvas — the classic digital rain.',
    category: 'Heroes',
    kind: 'motion',
  },
  {
    slug: 'bubble-stream',
    name: 'Bubble Stream',
    description: 'Wobbling bubbles rising with highlight glints on canvas.',
    category: 'Heroes',
    kind: 'motion',
  },
  {
    slug: 'aurora-curtain',
    name: 'Aurora Curtain',
    description: 'Shader curtain swaying like polar lights over a starfield.',
    category: 'Backgrounds',
    kind: 'motion',
    install: 'npm install three @types/three',
  },
  {
    slug: 'plasma',
    name: 'Plasma',
    description: 'Classic four-octave plasma shader flowing through two colors.',
    category: 'Backgrounds',
    kind: 'motion',
    install: 'npm install three @types/three',
  },
  {
    slug: 'color-waves',
    name: 'Color Waves',
    description: 'Three thick sine ribbons crossing at different speeds on canvas.',
    category: 'Backgrounds',
    kind: 'motion',
  },
  {
    slug: 'bokeh-lights',
    name: 'Bokeh Lights',
    description: 'Soft pulsing light orbs drifting upward on a dark field.',
    category: 'Backgrounds',
    kind: 'motion',
  },
  {
    slug: 'loader-dots',
    name: 'Dots Loader',
    description: 'Three dots hopping in sequence.',
    category: 'Loaders',
    kind: 'motion',
  },
  {
    slug: 'loader-ring',
    name: 'Ring Loader',
    description: 'Dual-color ring spinning on a track.',
    category: 'Loaders',
    kind: 'motion',
  },
  {
    slug: 'loader-bars',
    name: 'Bars Loader',
    description: 'Five gradient bars scaling in a wave.',
    category: 'Loaders',
    kind: 'motion',
  },
  {
    slug: 'loader-orbit-css',
    name: 'Orbit CSS Loader',
    description: 'Two counter-rotating orbit rings, pure CSS.',
    category: 'Loaders',
    kind: 'motion',
  },
  {
    slug: 'loader-liquid',
    name: 'Liquid Loader',
    description: 'Morphing blob filling with a rotating wave.',
    category: 'Loaders',
    kind: 'motion',
  },
  {
    slug: 'loader-flip',
    name: 'Flip Loader',
    description: 'Squares flipping through X and Y rotations.',
    category: 'Loaders',
    kind: 'motion',
  },
  {
    slug: 'motion-typewriter',
    name: 'Typewriter',
    description: 'Types, pauses, deletes with a blinking block caret.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-wave-text',
    name: 'Wave Text',
    description: 'Characters ride a sine wave of position and color.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-click-burst',
    name: 'Click Burst',
    description: 'Confetti shards explode from every click point.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-hover-reveal',
    name: 'Hover Reveal',
    description: 'A floating image card follows the cursor across list items.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-progress-scrub',
    name: 'Progress Scrub',
    description: 'Sticky progress bar mapped 1:1 to panel scroll via scrub.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-stagger-grid',
    name: 'Stagger Grid',
    description: 'A 3×3 grid popping from center outward, then breathing.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-cursor-blob',
    name: 'Cursor Blob',
    description: 'Blend-mode cursor blob that swells over interactive targets.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-elastic-nav',
    name: 'Elastic Nav',
    description: 'Nav items stretch and squash as neighbors react on hover.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-shine-button',
    name: 'Shine Button',
    description: 'A skewed sheen sweeps across the button on each hover.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-scrub-text',
    name: 'Scrub Text',
    description: 'Words illuminate one by one, scrubbed by scroll position.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-split-flap',
    name: 'Split Flap Board',
    description: 'Airport-style flaps spinning into a message with amber glow.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'motion-pendulum',
    name: 'Pendulum',
    description: 'Newton-cradle style swinging balls on a rail.',
    category: 'Motion',
    kind: 'motion',
    install: 'npm install gsap',
  },
  {
    slug: 'd25-tilt-card',
    name: 'Tilt Card',
    description: 'rAF-smoothed 3D tilt with a radial glare that tracks the cursor.',
    category: '2.5D',
    kind: 'motion',
  },
  {
    slug: 'd25-layered-scene',
    name: 'Layered Scene',
    description: 'Moonlit mountain layers drifting at different depths.',
    category: '2.5D',
    kind: 'motion',
  },
  {
    slug: 'd25-depth-fan',
    name: 'Depth Fan',
    description: 'Card stack fanning out in 3D space on hover.',
    category: '2.5D',
    kind: 'motion',
  },
  {
    slug: 'd25-room-window',
    name: 'Room Window',
    description: 'A framed window whose sky, sun, and hills shift against you.',
    category: '2.5D',
    kind: 'motion',
  },
  {
    slug: 'd25-hologram-panel',
    name: 'Hologram Panel',
    description: 'Sci-fi HUD tilting in perspective with scanline shimmer.',
    category: '2.5D',
    kind: 'motion',
  },
  {
    slug: 'd25-moving-shadow',
    name: 'Moving Shadow',
    description: 'Cursor acts as the light source; object skew and shadow respond.',
    category: '2.5D',
    kind: 'motion',
  },
  {
    slug: 'd25-popup-book',
    name: 'Popup Book',
    description: 'Paper pieces fold up off the page with drop shadows on hover.',
    category: '2.5D',
    kind: 'motion',
  },
  {
    slug: 'd25-city-blocks',
    name: 'City Blocks',
    description: 'Isometric city grid where buildings light up under the cursor.',
    category: '2.5D',
    kind: 'motion',
  },
  {
    slug: 'd25-floating-light',
    name: 'Floating Light',
    description: 'An orb bobbing over a floor whose glow and shadow track it.',
    category: '2.5D',
    kind: 'motion',
  },
  {
    slug: 'd25-extruded-badge',
    name: 'Extruded Badge',
    description: 'Badge with layered extrusion planes shearing on mouse move.',
    category: '2.5D',
    kind: 'motion',
  },
  {
    slug: 'button-toggle-switch',
    name: 'Toggle Switch',
    description: 'Springy role=switch with knob pop animation on toggle.',
    category: 'Buttons',
    kind: 'motion',
  },
  {
    slug: 'button-copy-feedback',
    name: 'Copy Button',
    description: 'Command pill that confirms with a checkmark flash after copying.',
    category: 'Buttons',
    kind: 'motion',
  },
  {
    slug: 'button-slide-text',
    name: 'Slide Text Button',
    description: 'Label rolls up to reveal metadata on hover through a clipped window.',
    category: 'Buttons',
    kind: 'motion',
  },
  {
    slug: 'effect-chromatic-hover',
    name: 'Chromatic Hover',
    description: 'Text splits into cyan/magenta fringes via text-shadow transition.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-vignette-panel',
    name: 'Vignette Panel',
    description: 'Colorful gradient field darkened by a heavy inset shadow vignette.',
    category: 'Effects',
    kind: 'motion',
  },
  {
    slug: 'effect-input-glow',
    name: 'Input Glow',
    description: 'Email input whose blurred gradient halo ignites on focus.',
    category: 'Effects',
    kind: 'motion',
  },
];

export const categories: ElementCategory[] = [
  'Motion',
  '2.5D',
  'Buttons',
  'Effects',
  'Loaders',
  'Elementals',
  'Backgrounds',
  'Objects',
  'Heroes',
  'Vector',
  'Shapes',
  'Textures',
  'Isometric',
  'Avatars',
  'Monsters',
];

export function getElement(slug: string): ElementMeta | undefined {
  return elements.find((e) => e.slug === slug);
}

export function byCategory(cat: ElementCategory): ElementMeta[] {
  return elements.filter((e) => e.category === cat);
}
